# Generated by Django 3.1.4 on 2021-01-11 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_keyword', models.CharField(default='', max_length=100)),
                ('tweet_id', models.CharField(max_length=30)),
                ('tweet_text', models.CharField(max_length=280)),
            ],
        ),
    ]
