# Generated by Django 3.1.4 on 2021-01-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210111_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='user',
        ),
    ]
