# Generated by Django 3.1.4 on 2021-01-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210124_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='isSaved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweets',
            name='saved_search_alias',
            field=models.CharField(default='', max_length=256),
        ),
    ]
