# Generated by Django 3.1.4 on 2021-01-30 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_tweets_tweet_text_lemma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='query_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 30, 7, 54, 16, 828807, tzinfo=utc)),
        ),
    ]
