# Generated by Django 3.1.4 on 2021-01-30 08:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210130_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='query_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 30, 8, 0, 18, 642408, tzinfo=utc)),
        ),
    ]
