# Generated by Django 3.1.4 on 2021-01-30 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210130_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='query_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
